# Generated by Django 5.1.5 on 2025-02-26 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Workout Name')),
                ('duration', models.PositiveIntegerField(verbose_name='Duration (minutes)')),
                ('calories', models.PositiveIntegerField(verbose_name='Calories burned')),
                ('description', models.TextField(verbose_name='Workout Description')),
                ('intensity_level', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=10, verbose_name='Workout Intensity')),
                ('category', models.CharField(choices=[('Cardio', 'Cardio'), ('Strength', 'Strength'), ('Flexibility', 'Flexibility'), ('Balance', 'Balance')], max_length=20, verbose_name='Workout Category')),
                ('exercise', models.ManyToManyField(to='FitnessPlan.exercise', verbose_name='Exercises')),
            ],
        ),
    ]
