# Generated by Django 5.1.5 on 2025-02-27 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitnessPlan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='calories',
            field=models.PositiveIntegerField(default=0, verbose_name='Calories burned'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='category',
            field=models.CharField(choices=[('Cardio', 'Cardio'), ('Strength', 'Strength'), ('Flexibility', 'Flexibility'), ('Balance', 'Balance')], default='Unknown', max_length=20, verbose_name='Workout Category'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='duration',
            field=models.PositiveIntegerField(default=0, verbose_name='Duration (minutes)'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='intensity_level',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Unknown', max_length=10, verbose_name='Workout Intensity'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='description',
            field=models.TextField(verbose_name='Exercise Description'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Exercise Name'),
        ),
        migrations.CreateModel(
            name='WorkoutPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout_name', models.CharField(max_length=255, verbose_name='Workout Name')),
                ('description', models.TextField(verbose_name='Workout Description')),
                ('duration', models.PositiveIntegerField(default=0, verbose_name='Duration (minutes)')),
                ('calories', models.PositiveIntegerField(default=0, verbose_name='Calories burned')),
                ('intensity_level', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Unknown', max_length=10, verbose_name='Workout Intensity')),
                ('category', models.CharField(choices=[('Cardio', 'Cardio'), ('Strength', 'Strength'), ('Flexibility', 'Flexibility'), ('Balance', 'Balance')], default='Unknown', max_length=20, verbose_name='Workout Category')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('exercise', models.ManyToManyField(to='FitnessPlan.exercise', verbose_name='Exercises')),
            ],
        ),
        migrations.DeleteModel(
            name='Workout',
        ),
    ]
