# Generated by Django 5.1.5 on 2025-03-02 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitnessPlan', '0002_exercise_calories_exercise_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Category Name')),
            ],
        ),
        migrations.CreateModel(
            name='BrowseWorkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Exercise Name')),
                ('description', models.TextField(verbose_name='Exercise Dexcription')),
                ('duration', models.PositiveIntegerField(default=0, verbose_name='Duration (minutes)')),
                ('calories', models.PositiveIntegerField(default=0, verbose_name='Calories burned')),
                ('intensity_level', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Unknown', max_length=20, verbose_name='Workout Intensity')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='FitnessPlan.category')),
            ],
            options={
                'ordering': ['name', 'duration', 'intensity_level'],
            },
        ),
    ]
