# Generated by Django 5.1.5 on 2025-03-07 19:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitnessPlan', '0003_category_browseworkout'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='browseworkout',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorite_exercises', to=settings.AUTH_USER_MODEL),
        ),
    ]
