# Generated by Django 5.1.5 on 2025-03-15 20:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitnessPlan', '0005_alter_browseworkout_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FitnessPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_content', models.TextField(verbose_name='Personalized Fitness Plan Details')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Update Time')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fitness_plans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
