# Generated by Django 5.1.4 on 2025-02-01 01:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MealPlan', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DietaryRestrictions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vegetarian', models.BooleanField(default=False)),
                ('Vegan', models.BooleanField(default=False)),
                ('Gluten_Free', models.BooleanField(default=False)),
                ('Lactose_Free', models.BooleanField(default=False)),
                ('Nut_Free', models.BooleanField(default=False)),
                ('Shellfish_Free', models.BooleanField(default=False)),
                ('Soy_Free', models.BooleanField(default=False)),
                ('Egg_Free', models.BooleanField(default=False)),
                ('Pork_Free', models.BooleanField(default=False)),
                ('Beef_Free', models.BooleanField(default=False)),
                ('Fish_Free', models.BooleanField(default=False)),
                ('Poultry_Free', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dietary_restrictions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
