# Generated by Django 5.1.4 on 2025-02-01 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MealPlan', '0002_dietaryrestrictions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dietaryrestrictions',
            old_name='Beef_Free',
            new_name='is_beef_free',
        ),
        migrations.RenameField(
            model_name='dietaryrestrictions',
            old_name='Egg_Free',
            new_name='is_egg_free',
        ),
        migrations.RenameField(
            model_name='dietaryrestrictions',
            old_name='Fish_Free',
            new_name='is_fish_free',
        ),
        migrations.RenameField(
            model_name='dietaryrestrictions',
            old_name='Gluten_Free',
            new_name='is_gluten_Free',
        ),
        migrations.RenameField(
            model_name='dietaryrestrictions',
            old_name='Lactose_Free',
            new_name='is_lactose_Free',
        ),
        migrations.RenameField(
            model_name='dietaryrestrictions',
            old_name='Nut_Free',
            new_name='is_nut_Free',
        ),
        migrations.RenameField(
            model_name='dietaryrestrictions',
            old_name='Pork_Free',
            new_name='is_pork_free',
        ),
        migrations.RenameField(
            model_name='dietaryrestrictions',
            old_name='Poultry_Free',
            new_name='is_poultry_free',
        ),
        migrations.RenameField(
            model_name='dietaryrestrictions',
            old_name='Shellfish_Free',
            new_name='is_shellfish_Free',
        ),
        migrations.RenameField(
            model_name='dietaryrestrictions',
            old_name='Soy_Free',
            new_name='is_soy_free',
        ),
        migrations.RenameField(
            model_name='dietaryrestrictions',
            old_name='Vegan',
            new_name='is_vegan',
        ),
        migrations.RenameField(
            model_name='dietaryrestrictions',
            old_name='Vegetarian',
            new_name='is_vegetarian',
        ),
    ]
