# Generated by Django 5.1.5 on 2025-02-04 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MealPlan', '0003_rename_beef_free_dietaryrestrictions_is_beef_free_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
