# Generated by Django 5.1.5 on 2025-02-04 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MealPlan', '0004_budgetmeal'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='budgetmeal',
            table='budget_meal',
        ),
    ]
