# Generated by Django 5.1.5 on 2025-02-05 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MealPlan', '0005_alter_budgetmeal_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='DietaryRestrictions_MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('calories', models.IntegerField(help_text='Calories per serving')),
                ('protein', models.FloatField(help_text='Protein in grams')),
                ('is_vegetarian', models.BooleanField(default=False)),
                ('is_vegan', models.BooleanField(default=False)),
                ('contains_gluten', models.BooleanField(default=False)),
                ('contains_lactose', models.BooleanField(default=False)),
                ('contains_nuts', models.BooleanField(default=False)),
                ('contains_shellfish', models.BooleanField(default=False)),
                ('contains_soy', models.BooleanField(default=False)),
                ('contains_eggs', models.BooleanField(default=False)),
                ('contains_pork', models.BooleanField(default=False)),
                ('contains_beef', models.BooleanField(default=False)),
                ('contains_fish', models.BooleanField(default=False)),
                ('contains_poultry', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='dietaryrestrictions',
            name='meal_plans',
            field=models.ManyToManyField(blank=True, to='MealPlan.dietaryrestrictions_mealplan'),
        ),
    ]
