# Generated by Django 5.1.5 on 2025-02-07 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MealPlan', '0006_dietaryrestrictions_mealplan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Meal Name')),
                ('preparation_time', models.IntegerField(verbose_name='Preparation Time (minutes)')),
                ('cooking_materials', models.TextField(verbose_name='Cooking Materials')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
