# Generated by Django 5.1.5 on 2025-02-08 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MealPlan', '0008_campusoptions_restaurant_campusoptions_menuitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campusoptions_restaurant',
            name='rating',
            field=models.FloatField(default=0.0, verbose_name='Restaurant Rating'),
        ),
    ]
