# Generated by Django 5.1.5 on 2025-02-12 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MealPlan', '0009_alter_campusoptions_restaurant_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealInstructions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=10)),
                ('dietary_restrictions', models.CharField(blank=True, help_text='Comma-separated dietary restrictions. (e.g., vegan, gluten-free)', max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('prepare_time', models.PositiveIntegerField(help_text='Preparation time in minutes.')),
                ('calories', models.PositiveIntegerField()),
                ('protein', models.PositiveIntegerField(help_text='Protein content in grams')),
                ('steps', models.TextField(help_text='Step-by-step meal preparation instructions')),
            ],
        ),
    ]
