# Generated by Django 5.1.5 on 2025-02-21 20:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MealPlan', '0010_mealinstructions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetmeal',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='campusoptions_menuitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='campusoptions_restaurant',
            name='rating',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Restaurant Rating'),
        ),
        migrations.AlterField(
            model_name='dietaryrestrictions_mealplan',
            name='calories',
            field=models.PositiveIntegerField(help_text='Calories per serving'),
        ),
        migrations.AlterField(
            model_name='dietaryrestrictions_mealplan',
            name='protein',
            field=models.FloatField(help_text='Protein in grams', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='mealinstructions',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='quickmeal',
            name='preparation_time',
            field=models.PositiveIntegerField(verbose_name='Preparation Time (minutes)'),
        ),
    ]
