# Generated by Django 5.1.5 on 2025-04-07 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MealPlan', '0011_alter_budgetmeal_price_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BudgetMeal',
        ),
        migrations.DeleteModel(
            name='QuickMeal',
        ),
    ]
