# Generated by Django 5.1.5 on 2025-04-07 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MealPlan', '0012_delete_budgetmeal_delete_quickmeal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MealInstructions',
        ),
        migrations.DeleteModel(
            name='MealplanSearchbar',
        ),
    ]
