# Generated by Django 5.1.5 on 2025-04-07 06:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MealPlan', '0013_delete_mealinstructions_delete_mealplansearchbar'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietaryrestrictions_mealplan',
            name='difficulty',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Easy', max_length=50),
        ),
        migrations.AddField(
            model_name='dietaryrestrictions_mealplan',
            name='prepare_time',
            field=models.PositiveIntegerField(default=0, help_text='Preparation time in minutes'),
        ),
        migrations.AddField(
            model_name='dietaryrestrictions_mealplan',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Meal price in dollars', max_digits=6, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='dietaryrestrictions_mealplan',
            name='steps',
            field=models.TextField(default='', help_text='Step-by-step preparation instructions'),
        ),
    ]
