# Generated by Django 5.1.5 on 2025-02-13 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ProgressTracking", "0005_exerciserecord"),
    ]

    operations = [
        migrations.AddField(
            model_name="gymgoal",
            name="goal_date",
            field=models.DateField(auto_now=True),
        ),
        migrations.DeleteModel(
            name="ExerciseRecord",
        ),
    ]
