# Generated by Django 5.1.5 on 2025-03-13 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ProgressTracking", "0006_gymgoal_goal_date_delete_exerciserecord"),
    ]

    operations = [
        migrations.CreateModel(
            name="FitnessActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "exercise_type",
                    models.CharField(
                        choices=[
                            ("cardio", "Cardio"),
                            ("weight_lifting", "Weight Lifting"),
                            ("yoga", "Yoga"),
                            ("pilates", "Pilates"),
                            ("hiit", "HIIT"),
                            ("cycling", "Cycling"),
                            ("swimming", "Swimming"),
                            ("running", "Running"),
                            ("rowing", "Rowing"),
                            ("boxing", "Boxing"),
                            ("dancing", "Dancing"),
                            ("strength_training", "Strength Training"),
                            ("crossfit", "CrossFit"),
                            ("stretching", "Stretching"),
                            ("elliptical_trainer", "Elliptical Trainer"),
                        ],
                        help_text="Type of exercise.",
                        max_length=30,
                    ),
                ),
                (
                    "recommended_duration_minutes",
                    models.PositiveIntegerField(
                        help_text="Recommended duration (in minutes) for the activity."
                    ),
                ),
                (
                    "calories_per_minute",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Estimated calories burned per minute.",
                        max_digits=5,
                    ),
                ),
                (
                    "difficulty_level",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                        ],
                        help_text="Difficulty level of the activity.",
                        max_length=10,
                    ),
                ),
                (
                    "target_category",
                    models.CharField(
                        blank=True,
                        help_text="Primary target category (e.g., cardiovascular, strength, flexibility).",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of the activity.", null=True
                    ),
                ),
            ],
            options={
                "db_table": "fitness_activity",
            },
        ),
    ]
