# Generated by Django 5.1.5 on 2025-04-01 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProgressTracking', '0008_award_badge_useraward_userbadge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='icon',
            field=models.ImageField(blank=True, default='awards/default_badge.png', null=True, upload_to='awards/'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='icon',
            field=models.ImageField(blank=True, default='badges/default_badge.png', null=True, upload_to='badges/'),
        ),
    ]
