# Generated by Django 5.1.5 on 2025-04-01 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProgressTracking', '0009_alter_award_icon_alter_badge_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='icon',
            field=models.ImageField(blank=True, default='awards/default_award.png', null=True, upload_to='awards/'),
        ),
    ]
