# Generated by Django 5.1.5 on 2025-04-06 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ProgressTracking", "0010_alter_award_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="gymgoal",
            name="calisthenics",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="gymgoal",
            name="hiking",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="gymgoal",
            name="jump_rope",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="gymgoal",
            name="kickboxing",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="gymgoal",
            name="mountain_climbers",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="gymgoal",
            name="power_yoga",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="gymgoal",
            name="sled_push",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="gymgoal",
            name="tai_chi",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="gymgoal",
            name="trx_training",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="gymgoal",
            name="water_aerobics",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="gymgoal",
            name="zumba",
            field=models.FloatField(default=0),
        ),
    ]
