# Generated by Django 5.1.5 on 2025-04-07 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProgressTracking', '0011_gymgoal_calisthenics_gymgoal_hiking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisesession',
            name='exercise_type',
            field=models.CharField(choices=[('cardio', 'Cardio'), ('weight_lifting', 'Weight Lifting'), ('yoga', 'Yoga'), ('pilates', 'Pilates'), ('hiit', 'HIIT'), ('cycling', 'Cycling'), ('swimming', 'Swimming'), ('running', 'Running'), ('rowing', 'Rowing'), ('boxing', 'Boxing'), ('dancing', 'Dancing'), ('strength_training', 'Strength Training'), ('crossfit', 'CrossFit'), ('stretching', 'Stretching'), ('elliptical_trainer', 'Elliptical Trainer'), ('kickboxing', 'Kickboxing'), ('calisthenics', 'Calisthenics'), ('tai_chi', 'Tai Chi'), ('mountain_climbers', 'Mountain Climbers'), ('trx_training', 'TRX Training'), ('power_yoga', 'Power yoga'), ('hiking', 'Hiking'), ('sled_push', 'Sled Push'), ('water_aerobics', 'Water Aerobics'), ('zumba', 'Zumba'), ('jump_rope', 'Jump Rope')], max_length=50),
        ),
        migrations.AlterField(
            model_name='fitnessactivity',
            name='exercise_type',
            field=models.CharField(choices=[('cardio', 'Cardio'), ('weight_lifting', 'Weight Lifting'), ('yoga', 'Yoga'), ('pilates', 'Pilates'), ('hiit', 'HIIT'), ('cycling', 'Cycling'), ('swimming', 'Swimming'), ('running', 'Running'), ('rowing', 'Rowing'), ('boxing', 'Boxing'), ('dancing', 'Dancing'), ('strength_training', 'Strength Training'), ('crossfit', 'CrossFit'), ('stretching', 'Stretching'), ('elliptical_trainer', 'Elliptical Trainer'), ('kickboxing', 'Kickboxing'), ('calisthenics', 'Calisthenics'), ('tai_chi', 'Tai Chi'), ('mountain_climbers', 'Mountain Climbers'), ('trx_training', 'TRX Training'), ('power_yoga', 'Power yoga'), ('hiking', 'Hiking'), ('sled_push', 'Sled Push'), ('water_aerobics', 'Water Aerobics'), ('zumba', 'Zumba'), ('jump_rope', 'Jump Rope')], help_text='Type of exercise.', max_length=30),
        ),
    ]
