# Generated by Django 5.1.5 on 2025-03-23 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_customuser_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='dietary_preference',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='fitness_preference',
        ),
    ]
